# Generated by Django 3.2.4 on 2021-06-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_last_request_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_request_time',
            new_name='last_activity',
        ),
    ]
